[package]
name = "domaintemplate"
version = "0.1.0"
edition = "2021"

[workspace]
members = ["domain", "application", "infrastructure"]

[dependencies]
domain = { path = "domain" }
application ={ path = "application"}