@host = http://127.0.0.1:8000/api/v1

POST {{host}}/auth/register
Content-Type: application/json

{
    "first_name":"Marco",
    "last_name":"Iorio",
    "email": "mi@example.com",
    "password": "myPassword123"
}